config/routes.rb
Rails.application.routes.draw do
  # Topページとそこからのリンク
  root 'home#ajax'
  get 'greeting' => 'home#greeting'
  get 'event'    => 'home#event'
  get 'contact'  => 'home#contact'
  get "top" => 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top

  end

  def greeting
  end

  def contact
  end

  def event
  end

  def ajax

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/ajax.html.erb
<!-- ajax_text -->
<%= render "shared/sidebar" %>
<div id="fh5co-main">
<%= render "shared/screen" %>
<%= render "shared/header" %>
<div class="pageDisplay">
</div>
<div class="Remote">
</div>
<%= render "shared/fooder" %>
<!-- end -->








<script>
// ajax_test
	//ページを表示させる箇所の設定
	var $content = $('.pageDisplay');
	//ボタンをクリックした時の処理
	$(document).on('click', '.gnavi a', function(event) {
		//バー消す
		 $('.gnavi li' ).removeClass("fh5co-active");
		 //クリックしたところのバーを追加
		 $(this).addClass("fh5co-active");
		event.preventDefault();
		//.gnavi aのhrefにあるリンク先を保存
		var link = $(this).attr("href");
		//リンク先が今と同じであれば遷移しない
		if(link == lastpage){
			$('li' ).removeClass("fh5co-active");
			return false;
		}else{
			$content.fadeOut(600, function() {
				getPage(link);
			});
			//今のリンク先を保存
			lastpage = link;
		}

	});
	//初期設定
	getPage("top");
	var lastpage = "top";

	//ページを取得してくる
    function getPage(elm){
    	$.ajax({
            type: 'GET',
            url: elm,
            dataType: 'html',
            success: function(data){
                $content.html(data).fadeIn(600);
            },
            error:function() {
                       alert('問題がありました。');
                   }
    	});
    }
</script>

app/views/home/contact.html.erb
this is contact

app/views/home/event.html.erb
this is event

app/views/home/greeting.html.erb
<h1>Ajax#index</h1>
<p id="hoge">赤色になるよ</p>

<script>
  $("#hoge").css("color","red")
</script>

app/views/home/top.html.erb
<section  class="fh5co-narrow-content_2">
  <div class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">
<!-- お知らせ -->
    <div class="infomation ">
      <img src="assets/infomation.png" class="img-responsive" width="200px" height="200px">
      <div class = "row">
        <div class="col-md-10 col-md-offset-1 ">
        <div class="box_title"></div>
        <div class="box_srcollbar">
            <p>10/06　■■■■■■が再入荷しました。<p>
            <p>10/05　○○○を追加しました。<p>
            <p>10/04　■■■ を追加しました。<p>
            <p>10/03　○○■■■○が再入荷しました。<p>
            <p>10/02　○■■■■■■○○が再入荷しました。<p>
            <p> 10/01　○○○が再入荷しました。<p>
        </div>
      </div>
    </div>
    </div>
  </div>
</section>
<!-- end -->

<section class="fh5co-narrow-content_2" >
<div class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">
      <img src="assets/suri2.png" class="img-responsive" width="200px" height="200px">
      <img src="assets/suri1.png" class="img-responsive">
<div class="acsess">
  <img src="assets/access.png" class="img-responsive" width="200px" height="200px">
  <div class="acsess-top">
    <div class="pull-left">
  <p>〒：300-3564</p><p>
  <p>住所：茨城県八千代町水口288<p>
  <p>TEL：090-4934-5541<p>
  </div>
  <div class="pull-right">
   <img src="assets/map.png" class="img-responsive" >
</div>
</div>
</div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Harukun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- jquery -->
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <script type="text/javascript" src="../script.js"></script> -->
    <!-- end -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="//maps.google.com/maps/api/js?key=<%= ENV['AIzaSyARKf8NDwzTZiU0PStNODA4DqzIeWv2_54'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script> -->
  </head>

  <body>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_fooder.html.erb
  <div class="fh5co-narrow-content_1">
    <div class="row">
      <div class="col-md-12">
        <div class="heading3">
          <img src="/assets/logo.png"  width="50px" height="50px" style="margin-top: 42px;">
      <p>&copy;Copyright Haukun_Japan_International. ALL rights reserved.</p>
  </div>
  </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <section class="aboutus animate-box section" id="aboutus" style="background-color: #F5F5F5;">
    <div class="fh5co-narrow-content_1">
      <div class="row">
        <div class="col-md-12">
          <div class="heading3">
            <h2>Harukun Group
            </h2>
            <img src="/assets/headerr.png" class="img-responsive">
            <!-- <img src="assets/header.png"> -->
          </div>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_header.html.erb
<header>
  <section class="aboutus animate-box section" id="aboutus" style="background-color: #F5F5F5;">
    <div class="fh5co-narrow-content_1">
      <div class="row">
        <div class="col-md-12">
          <div class="heading3">
            <h2>Harukun Group
            </h2>
            <img src="/assets/headerr.png" class="img-responsive">
            <!-- <img src="assets/header.png"> -->
          </div>
        </div>
      </div>
    </div>
  </section>
</header>

app/views/shared/_screen.html.erb
<div class="fh5co-narrow-content">
  <div class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">
    <!--スライド-->
    <section id="header-slider" class="section">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="assets/screen1.jpg" alt="Chania">
            <div class="carousel-caption">
              <p>We cannot do great things. But we can do small things with great love.
              </p>
            </div>
          </div>
          <div class="item">
            <img src="assets/screen2.jpg" alt="Chania">
            <div class="carousel-caption">
              <p>No one saves us but ourselves. No one can and no one may.
              </p>
            </div>
          </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon " aria-hidden="true"></span>
          <span class="sr-only">Previous</span></a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon " aria-hidden="true"></span>
          <span class="sr-only">Next</span></a>
      </div>
    </section>

  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="fh5co-page">
  <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
  <aside id="fh5co-aside" role="complementary" class="border js-fullheight">

    <h1 id="fh5co-logo"><a href="index.html"><img src="assets/logo.jpg" width = "190" height = "195"></a></h1>
    <nav id="fh5co-main-menu" role="navigation">

      <div class="gnavi">
      <ul>
        <li class="fh5co-active"><a href="top.html.erb">ホーム</a></li>
        <li ><a href="greeting.html.erb">ご挨拶</a></li>
        <li ><a href="contact.html.erb">お問い合わせ</a></li>
        <li ><a href="event.html.erb">イベント</a></li>
        <%= link_to "新規登録", top_path, remote: true %>
      </ul>
    </div>
    </nav>
  </aside>
</div>